apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster 
  region: ap-northeast-2 

managedNodeGroups:
  - name: as-is-node-group  # 새로운 노드 그룹 이름
    instanceType: m5.2xlarge  # As-is 노드 그룹 인스턴스 타입
    desiredCapacity: 1  # 기본 노드 수
    volumeSize: 20  # EBS 볼륨 크기
    privateNetworking: true  # 프라이빗 서브넷 사용
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true  # AutoScaler 권한 부여
