apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-nodes-binding
subjects:
  - kind: User
    name: "arn:aws:sts::590183712446:assumed-role/Admin/minjup-Isengard"  # 오류에 나오는 IAM 역할
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # 또는 필요한 클러스터 역할 (view는 읽기 권한을 의미)
  apiGroup: rbac.authorization.k8s.io
