apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster 
  region: ap-northeast-2 # 클러스터를 생성할 리전
  version: "1.30" # Kubernetes version

vpc:
  cidr: "10.0.0.0/16" # 클러스터에서 사용할 VPC의 CIDR
  nat:
    gateway: HighlyAvailable

managedNodeGroups:
  - name: node-group
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true  # This grants permissions for ALB
        autoScaler: true  # This grants permissions for autoscaling

cloudWatch:
  clusterLogging:
    enableTypes: ["*"] # Enable CloudWatch logging for debugging purposes

iam:
  withOIDC: true
